### PR TITLE
[BUGFIX] Use TYPO3 configured proxy for deepl client

### LINKED ISSUE #330: [BUG] add TYPO3 proxy support
**Describe the bug**
TYPO3 Serverproxy is not used to connect to deepl-api

**To Reproduce**
Use a TYPO3-Environment with Serverproxy configured,
seetings:  $GLOBALS['TYPO3_CONF_VARS'] ['HTTP']['proxy'] => 'http://server:port',
If I click the translate-buttons I get the spinning gif-icon followed by a timeout. 

**Expected behavior**
Serverproxy in TYPO3 should be used.

**Screenshots**
image

**TYPO3 Setup**
* TYPO3 Version 8.4.14
* Server apache
* Database type and version MariaDB-1:10.2.44+maria~bionic-log
* PHP version 8.1.27
* DeepL paid API
* composer

**Additional context**
we had this same issue on Dmitry Dulepov's deepl extension https://github.com/dmitryd/dd_deepl/issues/16
 
We use TYPO3 with proxy-settings $GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'].
the following very simple patch works (just demo) for me (added to the "orig-deepl"-code!).

vendor/deeplcom/deepl-php/src/Translator.php, line 81:
```
$this->client = new HttpClientWrapper(
    $serverUrl,
    $headers,
    $timeout,
    $maxRetries,
    $logger,
    'http://serverproxy.server.at:8991/',
    $http_client
);
```

### PR DESCRIPTION
**Pull request by NarkNiro**
When converting the client, the proxy configuration via TYPO3 was no longer taken into account. This will be made up for with this change.

resolve #330

### CODE REVIEW

File: Classes/AbstractClient.php [hunk 1]
```diff
@@ -43,7 +44,14 @@ protected function getTranslator(): Translator
             throw new ApiKeyNotSetException('The api key ist not set', 1708081233823);
         }
 
-        $this->translator = GeneralUtility::makeInstance(Translator::class, $this->configuration->getApiKey());
+        $options = [];
+        if (isset($GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy']) && $GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy'] !== '') {
```
Comment (sbuerk) [inline Classes/AbstractClient.php:48]: Both if() levels can and should be merged into one.

**Review by sbuerk — CHANGES_REQUESTED** [review]

**Review by sbuerk — APPROVED** [review]

**Comment by dirnbauer** [comment]
Thank you very much!
