### PR TITLE
[BUGFIX] Mitigate unrelated page traversal for glossary lookup

### LINKED ISSUE #334: [BUG] Performance problem with latest version in large site
**Describe the bug**
Using the latest version 4.3.1 (also reproducible with 4.2.1 and latest main), I noticed that the translation with DeepL takes very long, something between 25 seconds up to about 1 minute. This is not really usable.

To find the problem I debugged / profiled and found out that the part that is taking so long is fetching the entire page tree for the site (!) in 

*GlossaryRepository::getGlossariesInRootByCurrentPage:*

```
$allPages = GeneralUtility::makeInstance(PageTreeRepository::class)
            ->getTreeList($rootPage, 999);

```

So, not the DeepL translation is taking so long. This is actually quite fast. Fetching all pages in a site for the glossary is causing the performance problems.

I am currently not using the glossary. The glossary is empty (no records).

**To Reproduce**

1. Use a site with many pages
2. translate content with "DeepL" button (not auto)

**Expected behavior**

I would expect:

- to make it possible to define a page for the glossary and deactivate recursive behaviour, but not seen a way to do that:
in` DeeplService::translateRequest`, if `sourceLanguage` is not "auto", the function `getGlossaryBySourceAndTarget` is called, which calls `getGlossary` with **recursive = true** (!)
- I don't see the need to fetch glossary entries on **every** translation request. This can be uploaded to DeepL once and maintained via a housekeeping script e.g. via cron or on demand
- ideally make it possible to deactivate the local glossary entirely  / upload a glossary via other service and use that

**Screenshots**

image

**TYPO3 Setup**
* TYPO3 Version: 11.5.37
* Server: Apache + php-fpm
* Database type and version: 10.4.19-MariaDB MariaDB Server
* PHP version: 8.2
* DeepL free or paid API: paid
* composer: yes
* Development context

**Additional context**

We were one of the sponsors for the glossary. (Carl von Ossietzky Universität Oldenburg). I have been using an older (patched) version of this extension. I would now like to update to latest version. I really like this extension and would like to use the new features. Not really happy with the disruption of a quite stable extension by adding (not production ready)  glossary feature, though.

### PR DESCRIPTION
**Pull request by NarkNiro**
Based on the concept the matching glossaries for the current site root tree should be used for translation process. Glossaries are managed on default pages with the `glossaries` module attached, thus are free to be defined within the page tree structure. Using a page traversal approach from the detected site root becomes really costly as it traverse the full page tree beneath the matched site root, thus becoming quickly quite costly.

Albeit not the best approach, retrieving pages with the module attached and using the SiteFinder and therefore the rootline to sort out module pages not included for the site root reduces the traversed and retrieved pages white a lot.

Note: With dropping TYPO3 v12 support it would be possible to use handcrafted common table expressions to further optimize that lookup and with TYPO3 v13 at least TYPO3 Core internal API may be available.

This change modifies the glossary id lookup method to exchange the pagetraversal approach with a flat record list rootline check approach as a first, quick and non breaking improvement. Instances not using the glossary feature avoids the recursive traversal at all with this implementation.

Resolve #334

### CODE REVIEW

File: Classes/Domain/Repository/GlossaryRepository.php [hunk 1]
```diff
@@ -470,33 +471,47 @@ private function getGlossary(
...
+                        Connection::PARAM_INT
+                    )
+                ),
                 $db->expr()->eq('module', $db->createNamedParameter('glossary'))
-            );
-        $result = $statement->executeQuery()->fetchAllAssociative();
+            )->executeQuery();
 
-        if (!is_array($result)) {
+        if ($result->rowCount() === 0) {
```
Comment (sbuerk) [inline Classes/Domain/Repository/GlossaryRepository.php:491]: SELECT->rowCount() should not be used. Either usa a dedicated count query first, or early return is not possible.

But instead of fetchAllAssociative() the core way is using `while($row = $result->fetchAssociative()) {}` instead of a foreach on all retrieved records.

**Review by sbuerk — CHANGES_REQUESTED** [review]

**Review by sbuerk — DISMISSED** [review]

**Review by sbuerk — APPROVED** [review]
